### ISSUE TITLE
Tool to track which directories are being accessed by the Linux file explorer?

### ISSUE THREAD

**Issue by sahildua2305** [ole-tange/tangetools#2]
Hi,

I have an idea which I have been trying to implement for some time now. It's about tracing the directories being opened in the Linux GUI file explorer. Is it possible to do any existing tool? Can you give me pointers regarding how to build such a tool?

**Comment by ole-tange** [comment]
MOVED TO https://gitlab.com/ole.tange/tangetools

https://gitlab.com/ole.tange/tangetools/issues/3
